/**
 * The city, extruded.
 *
 * Everything here is derived from the same `GameState` the 2D terminal uses —
 * no second source of truth. The simulation already works in metres with a
 * floor index, so the mapping is direct: sim `x` is world X, sim `y` is world
 * Z, and a floor becomes height. Nothing about the sim had to change to make it
 * three-dimensional, which is the whole reason it was built coordinate-first.
 */

import * as THREE from "three";

import type { GameState } from "../../src/sim/state.js";
import type { Building, District, Place } from "../../src/world/types.js";

export const FLOOR_HEIGHT = 3.6;

/**
 * Infill.
 *
 * The simulation models eight buildings across roughly a square mile. On a
 * top-down map that is a city; at eye level it is a business park with a lot of
 * car park between the sheds. So the gaps get filled with blocks that are
 * scenery and nothing else — no doors, no rooms, no network, nobody inside.
 *
 * They are the street wall, and the honest way to think about them is as the
 * *rest* of the city: the parts nothing in this game happens in. Everything the
 * game does happen in is still generated by `src/world/`, still has people in
 * it, and is still the only thing labelled.
 *
 * The cells are small on purpose. A cell that straddles a street is dropped
 * whole, so the grid's own coarseness *becomes* the street width: at 44 metres
 * a twenty-metre road came out over a hundred metres wide, and the city read as
 * a ring road with the buildings parked around the edge of it.
 */
const INFILL_CELL = 15;
const INFILL_STEP = 17;
/** Kerb to facade. A street is about twice this wide. */
const STREET_CLEARANCE = 10;
/** Buildings the game is played in get a bit more elbow room than a terrace. */
const BUILDING_CLEARANCE = 8;
const INFILL_CAPACITY = 4200;
const INFILL_WINDOW_CAPACITY = 14000;

export interface CityMeshes {
  root: THREE.Group;
  /** Solid things the player should not walk through. */
  colliders: THREE.Box3[];
  /** Buildings the simulation actually models, for the navigation labels. */
  landmarks: Array<{ name: string; position: THREE.Vector3 }>;
  /** Rooms open to the public, which are the ones you can walk into. */
  interiors: Interior[];
  /**
   * Everything that switches on after dark, with its own range — a streetlight
   * bulb and the pool of light it throws want very different numbers, and a
   * single shared opacity made one of them wrong at every hour.
   */
  lit: LitSurface[];
}

export interface LitSurface {
  material: THREE.Material;
  /** Opacity in full daylight. */
  day: number;
  /** Opacity at midnight. */
  night: number;
}

/**
 * Daylight, and a city that is made of something.
 *
 * The first pass was a permanent night in panel greys, and it rendered —
 * correctly and uselessly — black: a Lambert surface multiplies its colour by
 * the light, so a 10%-grey building under a 16%-grey ambient is 1.6% grey.
 *
 * These are surfaces rather than moods. Warm concrete, asphalt, painted lines,
 * glass. They read at noon *and* at midnight because `sky.ts` changes the light
 * rather than the paint, which is how it works outdoors.
 */
const PALETTE = {
  ground: 0x6f7168,
  district: 0x8e8d85,
  road: 0x4b4d51,
  markings: 0xd6d2c2,
  building: 0xb4ac9c,
  buildingLit: 0xc9c0ac,
  /** Glass, tinted the one colour this game has always been. */
  window: 0x35e0c8,
  kerb: 0xa5a196,
  infillWindow: 0xffdca6,
};

/**
 * The row.
 *
 * One grey repeated four hundred times is a warehouse estate, and it was the
 * single biggest thing between this and a city you would believe. Real terraces
 * are painted, individually, by people who were not consulting each other —
 * so the blocks draw from a spread of plausible facade colours and no two
 * neighbours are reliably alike.
 */
const FACADES = [
  0xd8cfbc, // cream
  0xc9b7a0, // sand
  0xb08d76, // terracotta
  0x9aa79c, // sage
  0x8fa3b8, // pale blue
  0xbfb0ae, // dusty pink
  0xa89a86, // stone
  0x7f8c96, // slate
  0xc4c0b4, // off-white
  0x94766a, // brick
];

/** Shopfronts are darker and glassier than the storeys above them. */
const SHOPFRONTS = [0x3d4a52, 0x4a3f3a, 0x2f4740, 0x53453c, 0x36404d];

function box(w: number, h: number, d: number, colour: number, opts: { emissive?: number } = {}) {
  const material = new THREE.MeshLambertMaterial({
    color: colour,
    ...(opts.emissive ? { emissive: opts.emissive, emissiveIntensity: 0.35 } : {}),
  });
  return new THREE.Mesh(new THREE.BoxGeometry(w, h, d), material);
}

/**
 * Windows up a facade.
 *
 * One material per facade, handed back to the caller, because the clock owns
 * how lit they are: near-transparent glass tint by day, burning by night. A
 * building whose windows do not change is the single loudest tell that a scene
 * is not really outdoors.
 */
function facadeWindows(building: Building, rng: () => number): THREE.InstancedMesh {
  const perFloor = Math.max(2, Math.floor(building.width / 14));
  const count = perFloor * building.floors * 2;
  const geometry = new THREE.PlaneGeometry(2.2, 1.4);
  const material = new THREE.MeshBasicMaterial({
    color: PALETTE.window,
    transparent: true,
    opacity: 0.5,
    fog: true,
  });
  const mesh = new THREE.InstancedMesh(geometry, material, count);
  const dummy = new THREE.Object3D();

  let i = 0;
  for (let floor = 0; floor < building.floors; floor++) {
    const y = floor * FLOOR_HEIGHT + FLOOR_HEIGHT * 0.55;
    for (let n = 0; n < perFloor; n++) {
      const t = (n + 0.5) / perFloor;
      for (const [side, rot] of [
        [1, 0],
        [-1, Math.PI],
      ] as const) {
        if (i >= count) break;
        dummy.position.set(
          building.x + t * building.width,
          y,
          building.y + (side > 0 ? building.depth + 0.1 : -0.1),
        );
        dummy.rotation.set(0, rot, 0);
        // Not every window is lit, and the pattern should not look regular.
        dummy.scale.setScalar(rng() > 0.45 ? 1 : 0.001);
        dummy.updateMatrix();
        mesh.setMatrixAt(i++, dummy.matrix);
      }
    }
  }
  mesh.instanceMatrix.needsUpdate = true;
  return mesh;
}

function addDistrict(root: THREE.Group, district: District): void {
  const mesh = box(district.width, 0.4, district.height, PALETTE.district);
  mesh.position.set(district.x + district.width / 2, -0.2, district.y + district.height / 2);
  mesh.receiveShadow = true;
  root.add(mesh);
}

/**
 * A room you can walk into.
 *
 * The client needs two things about an interior: the volume, so it knows when
 * you are inside one, and which places the simulation will let you stand in
 * while you are. Only `public` rooms qualify, which is not a simplification —
 * it is the access model. A lobby, a café floor, a bar, a clinic waiting room
 * and a shop floor are the rooms anybody may walk into; everything behind them
 * is semi, staff or restricted and still has to be earned.
 */
export interface Interior {
  buildingId: string;
  name: string;
  /** Walkable volume. Being inside it is how the client knows you are indoors. */
  bounds: THREE.Box3;
  /** Ground-floor public places you can be snapped to in here. */
  placeIds: string[];
  /** The pavement outside the door, and the spot just inside it. */
  approach: THREE.Vector3;
  entrance: THREE.Vector3;
}

/** Wall thickness, and the width of a doorway. */
const WALL = 0.5;
const DOORWAY = 5;
/** Eye height, so entrance markers land where a camera would. */
const EYE = 1.68;

function addBuilding(
  root: THREE.Group,
  state: GameState,
  building: Building,
  colliders: THREE.Box3[],
  lit: LitSurface[],
  interiors: Interior[],
  rng: () => number,
): void {
  const height = building.floors * FLOOR_HEIGHT;
  const bx = building.x;
  const bz = building.y;
  const bw = building.width;
  const bd = building.depth;

  const glass = facadeWindows(building, rng);
  lit.push({ material: glass.material as THREE.Material, day: 0.09, night: 0.8 });
  root.add(glass);

  const solid = (x0: number, z0: number, x1: number, z1: number, y0: number, y1: number, colour: number) => {
    if (x1 - x0 < 0.05 || z1 - z0 < 0.05 || y1 - y0 < 0.05) return;
    const mesh = box(x1 - x0, y1 - y0, z1 - z0, colour);
    mesh.position.set((x0 + x1) / 2, (y0 + y1) / 2, (z0 + z1) / 2);
    mesh.castShadow = true;
    mesh.receiveShadow = true;
    root.add(mesh);
    colliders.push(new THREE.Box3(new THREE.Vector3(x0, y0, z0), new THREE.Vector3(x1, y1, z1)));
  };

  const publicPlaces = state.city.graph
    .placesInBuilding(building.id)
    .filter((p) => p.floor === 0 && p.zone === "public");

  if (publicPlaces.length === 0) {
    // Nothing here is open to the public, so the building stays what it was: a
    // solid mass with a way in you have to make rather than walk through.
    solid(bx, bz, bx + bw, bz + bd, 0, height, PALETTE.building);
    const skirt = box(bw + 0.6, 1.4, bd + 0.6, PALETTE.buildingLit);
    skirt.position.set(bx + bw / 2, 0.7, bz + bd / 2);
    root.add(skirt);
    return;
  }

  // The doorway goes on whichever facade the public room is nearest, which is
  // where an architect would have put it and where the blueprint's own `u`/`v`
  // already says the room is.
  const room = publicPlaces[0]!;
  const gaps = [
    { side: "-z" as const, d: room.y - bz },
    { side: "+z" as const, d: bz + bd - room.y },
    { side: "-x" as const, d: room.x - bx },
    { side: "+x" as const, d: bx + bw - room.x },
  ].sort((a, b) => a.d - b.d);
  const facade = gaps[0]!.side;
  const alongX = facade === "-z" || facade === "+z";

  // The room spans the facade and reaches far enough in to contain the place
  // the simulation put there, with room to stand behind it.
  const REACH = 11;
  const inner = new THREE.Box3(
    new THREE.Vector3(
      alongX ? bx + WALL : facade === "-x" ? bx + WALL : Math.max(bx + WALL, room.x - REACH),
      0,
      alongX ? (facade === "-z" ? bz + WALL : Math.max(bz + WALL, room.y - REACH)) : bz + WALL,
    ),
    new THREE.Vector3(
      alongX ? bx + bw - WALL : facade === "+x" ? bx + bw - WALL : Math.min(bx + bw - WALL, room.x + REACH),
      FLOOR_HEIGHT,
      alongX ? (facade === "+z" ? bz + bd - WALL : Math.min(bz + bd - WALL, room.y + REACH)) : bz + bd - WALL,
    ),
  );
  if (facade === "-x") inner.max.x = Math.min(bx + bw - WALL, room.x + REACH);
  if (facade === "+x") inner.min.x = Math.max(bx + WALL, room.x - REACH);

  // Everything that is not the room, at ground level, stays solid — except the
  // strip the door is in, which is built separately with a gap in it. Filling
  // that strip here as well is exactly how the first version sealed every
  // doorway it had just carved.
  if (inner.min.z > bz && facade !== "-z") solid(bx, bz, bx + bw, inner.min.z, 0, FLOOR_HEIGHT, PALETTE.building);
  if (inner.max.z < bz + bd && facade !== "+z") solid(bx, inner.max.z, bx + bw, bz + bd, 0, FLOOR_HEIGHT, PALETTE.building);
  if (facade !== "-x") solid(bx, inner.min.z, inner.min.x, inner.max.z, 0, FLOOR_HEIGHT, PALETTE.building);
  if (facade !== "+x") solid(inner.max.x, inner.min.z, bx + bw, inner.max.z, 0, FLOOR_HEIGHT, PALETTE.building);

  // The facade the door is in, in two pieces with a gap between them.
  const mid = alongX ? (inner.min.x + inner.max.x) / 2 : (inner.min.z + inner.max.z) / 2;
  if (alongX) {
    const z0 = facade === "-z" ? bz : bz + bd - WALL;
    solid(inner.min.x, z0, mid - DOORWAY / 2, z0 + WALL, 0, FLOOR_HEIGHT, PALETTE.buildingLit);
    solid(mid + DOORWAY / 2, z0, inner.max.x, z0 + WALL, 0, FLOOR_HEIGHT, PALETTE.buildingLit);
  } else {
    const x0 = facade === "-x" ? bx : bx + bw - WALL;
    solid(x0, inner.min.z, x0 + WALL, mid - DOORWAY / 2, 0, FLOOR_HEIGHT, PALETTE.buildingLit);
    solid(x0, mid + DOORWAY / 2, x0 + WALL, inner.max.z, 0, FLOOR_HEIGHT, PALETTE.buildingLit);
  }

  // Everything above the ground floor is a solid mass, and it is what stops the
  // room reading as a shed with the rest of the building floating over it.
  if (height > FLOOR_HEIGHT) {
    solid(bx, bz, bx + bw, bz + bd, FLOOR_HEIGHT, height, PALETTE.building);
  }

  // Floor and ceiling. Both are visual only — you are already fenced in by the
  // walls, and a collider on the floor you stand on serves no purpose.
  const slab = (y: number, colour: number) => {
    const mesh = box(inner.max.x - inner.min.x, 0.2, inner.max.z - inner.min.z, colour);
    mesh.position.set((inner.min.x + inner.max.x) / 2, y, (inner.min.z + inner.max.z) / 2);
    root.add(mesh);
  };
  slab(0.1, 0x8a8378);
  slab(FLOOR_HEIGHT - 0.1, 0x6a655e);

  // Where the door is, in world terms. Useful to the client for a prompt, and
  // to the tests for the only question that matters about a doorway: can you
  // actually walk through it.
  const outward = facade === "-z" ? -1 : facade === "+z" ? 1 : 0;
  const sideways = facade === "-x" ? -1 : facade === "+x" ? 1 : 0;
  const doorX = alongX ? mid : facade === "-x" ? bx : bx + bw;
  const doorZ = alongX ? (facade === "-z" ? bz : bz + bd) : mid;
  interiors.push({
    buildingId: building.id,
    name: room.name,
    bounds: inner,
    placeIds: publicPlaces.map((p) => p.id),
    approach: new THREE.Vector3(doorX + sideways * 7, EYE, doorZ + outward * 7),
    entrance: new THREE.Vector3(doorX - sideways * 3, EYE, doorZ - outward * 3),
  });
}

/** Roads are drawn along the walkable graph, so the city you see is the city that exists. */
function addRoads(root: THREE.Group, state: GameState): void {
  const graph = state.city.graph;
  const drawn = new Set<string>();

  for (const edge of graph.edges.values()) {
    const a = graph.places.get(edge.a);
    const b = graph.places.get(edge.b);
    if (!a || !b || a.indoor || b.indoor) continue;
    const key = [edge.a, edge.b].sort().join("|");
    if (drawn.has(key)) continue;
    drawn.add(key);

    const dx = b.x - a.x;
    const dz = b.y - a.y;
    const length = Math.hypot(dx, dz);
    if (length < 1) continue;

    const heading = -Math.atan2(dz, dx);
    const road = box(length, 0.12, 22, PALETTE.road);
    road.position.set(a.x + dx / 2, 0.06, a.y + dz / 2);
    road.rotation.y = heading;
    root.add(road);

  }

  // A pad under each outdoor place so junctions and plazas read as somewhere.
  for (const place of graph.places.values()) {
    if (place.indoor) continue;
    const pad = new THREE.Mesh(
      new THREE.CircleGeometry(Math.max(12, place.radius * 0.8), 28),
      new THREE.MeshLambertMaterial({ color: PALETTE.kerb }),
    );
    pad.rotation.x = -Math.PI / 2;
    pad.position.set(place.x, 0.09, place.y);
    root.add(pad);
  }
}

/* ------------------------------------------------------------------ infill */

interface Rect {
  x0: number;
  z0: number;
  x1: number;
  z1: number;
}

/** Everywhere infill must not go: streets, plazas, and the real buildings. */
function keepClear(state: GameState): { rects: Rect[]; segments: Array<[number, number, number, number]> } {
  const rects: Rect[] = [];
  const segments: Array<[number, number, number, number]> = [];

  for (const building of state.city.buildings.values()) {
    rects.push({
      x0: building.x - BUILDING_CLEARANCE,
      z0: building.y - BUILDING_CLEARANCE,
      x1: building.x + building.width + BUILDING_CLEARANCE,
      z1: building.y + building.depth + BUILDING_CLEARANCE,
    });
  }

  const graph = state.city.graph;
  for (const place of graph.places.values()) {
    if (place.indoor) continue;
    // A plaza is not its whole footprint radius of open ground — that reading
    // put the nearest building 350 metres from the spawn point and produced a
    // skyline you could only ever look at.
    const r = place.radius * 0.62 + STREET_CLEARANCE;
    rects.push({ x0: place.x - r, z0: place.y - r, x1: place.x + r, z1: place.y + r });
  }
  for (const edge of graph.edges.values()) {
    const a = graph.places.get(edge.a);
    const b = graph.places.get(edge.b);
    if (!a || !b || a.indoor || b.indoor) continue;
    segments.push([a.x, a.y, b.x, b.y]);
  }

  return { rects, segments };
}

function rectsOverlap(a: Rect, b: Rect): boolean {
  return a.x0 < b.x1 && a.x1 > b.x0 && a.z0 < b.z1 && a.z1 > b.z0;
}

/**
 * Does a street run too close to this block?
 *
 * Measured rect-to-segment, by walking the road and clamping each point onto
 * the rect. Comparing centre-to-segment instead — the obvious version — adds
 * half a block width to every margin, which turned a twenty-metre street into a
 * hundred-metre clearing and hollowed out the middle of every district.
 */
function nearSegment(cell: Rect, seg: [number, number, number, number], margin: number): boolean {
  const [ax, az, bx, bz] = seg;
  const length = Math.hypot(bx - ax, bz - az);
  const steps = Math.max(2, Math.ceil(length / 8));
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    const px = ax + (bx - ax) * t;
    const pz = az + (bz - az) * t;
    const qx = Math.max(cell.x0, Math.min(cell.x1, px));
    const qz = Math.max(cell.z0, Math.min(cell.z1, pz));
    if (Math.hypot(px - qx, pz - qz) < margin) return true;
  }
  return false;
}

/**
 * Two instanced meshes for the entire background city: one for the blocks, one
 * for every lit window in all of them. Several hundred buildings at two draw
 * calls, which is the only reason this is affordable at all.
 */
function addInfill(
  root: THREE.Group,
  state: GameState,
  colliders: THREE.Box3[],
  litSurfaces: LitSurface[],
  rng: () => number,
): void {
  const clear = keepClear(state);
  const blocks = new THREE.InstancedMesh(
    new THREE.BoxGeometry(1, 1, 1),
    // A little emissive so the shaded side of a block never goes to pure black.
    new THREE.MeshLambertMaterial({ color: 0xffffff, emissive: 0x161a1e }),
    INFILL_CAPACITY,
  );
  const windows = new THREE.InstancedMesh(
    new THREE.PlaneGeometry(2.6, 1.7),
    new THREE.MeshBasicMaterial({ color: PALETTE.infillWindow, transparent: true, opacity: 0.6, fog: true }),
    INFILL_WINDOW_CAPACITY,
  );
  // A cornice: a slightly wider, darker slab on top. Two triangles' worth of
  // geometry, and the whole reason a block stops reading as an extruded
  // rectangle and starts reading as a building someone finished.
  const cornices = new THREE.InstancedMesh(
    new THREE.BoxGeometry(1, 1, 1),
    new THREE.MeshLambertMaterial({ color: 0x6f6a62 }),
    INFILL_CAPACITY,
  );
  // The ground floor is not the same as the floors above it. In a real street
  // it is glass, signage and a different colour entirely, and it is what your
  // eye is actually at the height of.
  const shops = new THREE.InstancedMesh(
    new THREE.BoxGeometry(1, 1, 1),
    new THREE.MeshLambertMaterial({ color: 0xffffff }),
    INFILL_CAPACITY,
  );
  const shopGlass = new THREE.InstancedMesh(
    new THREE.BoxGeometry(1, 1, 1),
    new THREE.MeshBasicMaterial({ color: 0x9fd8d2, transparent: true, opacity: 0.35, fog: true }),
    INFILL_CAPACITY * 2,
  );

  const dummy = new THREE.Object3D();
  const tint = new THREE.Color();
  const parked = new THREE.Vector3(0, -1000, 0);

  let block = 0;
  let lit = 0;
  let shopCount = 0;
  let glassCount = 0;

  for (const district of state.city.districts.values()) {
    for (let x = district.x + 8; x + INFILL_CELL < district.x + district.width - 8; x += INFILL_STEP) {
      for (let z = district.y + 8; z + INFILL_CELL < district.y + district.height - 8; z += INFILL_STEP) {
        if (block >= INFILL_CAPACITY) break;
        const cell: Rect = { x0: x, z0: z, x1: x + INFILL_CELL, z1: z + INFILL_CELL };
        if (clear.rects.some((r) => rectsOverlap(cell, r))) continue;
        if (clear.segments.some((s) => nearSegment(cell, s, STREET_CLEARANCE))) continue;

        // A skyline needs a distribution, not a mean: mostly low, occasionally
        // tall, and never the same twice down a street.
        const floors = 2 + Math.floor(rng() ** 2.4 * 12);
        const height = floors * FLOOR_HEIGHT;
        const width = INFILL_CELL - 1 - rng() * 2;
        const depth = INFILL_CELL - 1 - rng() * 2;
        const cx = x + INFILL_CELL / 2;
        const cz = z + INFILL_CELL / 2;

        dummy.position.set(cx, height / 2, cz);
        dummy.rotation.set(0, 0, 0);
        dummy.scale.set(width, height, depth);
        dummy.updateMatrix();
        blocks.setMatrixAt(block, dummy.matrix);
        // Painted individually, by people who were not consulting each other.
        tint.setHex(FACADES[Math.floor(rng() * FACADES.length)]!).offsetHSL(0, 0, (rng() - 0.5) * 0.07);
        blocks.setColorAt(block, tint);
        block++;

        // Cornice.
        dummy.position.set(cx, height + 0.35, cz);
        dummy.scale.set(width + 1.1, 0.7, depth + 1.1);
        dummy.updateMatrix();
        cornices.setMatrixAt(block - 1, dummy.matrix);

        // Shopfront, on the lower storeys of the shorter blocks.
        if (shopCount < INFILL_CAPACITY) {
          dummy.position.set(cx, 1.9, cz);
          dummy.scale.set(width + 0.5, 3.8, depth + 0.5);
          dummy.updateMatrix();
          shops.setMatrixAt(shopCount, dummy.matrix);
          tint.setHex(SHOPFRONTS[Math.floor(rng() * SHOPFRONTS.length)]!);
          shops.setColorAt(shopCount, tint);
          shopCount++;

          // Glazing on two faces, which is enough — you only ever see the
          // street side, and the other three are up against the next building.
          for (const [ox, oz, sx, sz] of [
            [0, (depth + 0.66) / 2, width * 0.72, 0.1],
            [(width + 0.66) / 2, 0, 0.1, depth * 0.72],
          ] as const) {
            if (glassCount >= INFILL_CAPACITY * 2) break;
            dummy.position.set(cx + ox, 2.1, cz + oz);
            dummy.scale.set(Math.max(0.1, sx), 2.1, Math.max(0.1, sz));
            dummy.updateMatrix();
            shopGlass.setMatrixAt(glassCount++, dummy.matrix);
          }
        }
        dummy.rotation.set(0, 0, 0);

        colliders.push(
          new THREE.Box3(
            new THREE.Vector3(cx - width / 2, 0, cz - depth / 2),
            new THREE.Vector3(cx + width / 2, height, cz + depth / 2),
          ),
        );

        for (let n = 0; n < floors * 2 && lit < INFILL_WINDOW_CAPACITY; n++) {
          if (rng() > 0.4) continue;
          const floor = 1 + Math.floor(rng() * Math.max(1, floors - 1));
          const side = Math.floor(rng() * 4);
          const along = (rng() - 0.5) * (side % 2 === 0 ? width : depth) * 0.7;
          const out = (side % 2 === 0 ? depth : width) / 2 + 0.12;
          dummy.position.set(
            cx + (side === 0 ? along : side === 2 ? along : side === 1 ? out : -out),
            floor * FLOOR_HEIGHT + FLOOR_HEIGHT * 0.5,
            cz + (side === 0 ? out : side === 2 ? -out : along),
          );
          dummy.rotation.set(0, (side * Math.PI) / 2, 0);
          dummy.scale.setScalar(1);
          dummy.updateMatrix();
          windows.setMatrixAt(lit++, dummy.matrix);
        }
      }
    }
  }

  // Counts rather than parked matrices where the mesh supports it — an
  // InstancedMesh only draws `count`, so unused slots cost nothing at all.
  blocks.count = block;
  cornices.count = block;
  shops.count = shopCount;
  shopGlass.count = glassCount;
  windows.count = lit;

  dummy.position.copy(parked);
  dummy.rotation.set(0, 0, 0);
  dummy.scale.setScalar(1);
  dummy.updateMatrix();

  for (const mesh of [blocks, cornices, shops, shopGlass, windows]) {
    mesh.instanceMatrix.needsUpdate = true;
    if (mesh.instanceColor) mesh.instanceColor.needsUpdate = true;
    // Scenery is never a target: keep it out of every raycast the client runs.
    mesh.raycast = () => {};
    root.add(mesh);
  }
  litSurfaces.push(
    { material: windows.material as THREE.Material, day: 0.04, night: 0.85 },
    { material: shopGlass.material as THREE.Material, day: 0.3, night: 0.6 },
  );
}

/* --------------------------------------------------------- street dressing */

/** Half the carriageway. Everything on a street is placed relative to this. */
const ROAD_HALF = 11;

/**
 * The things that make a road a street.
 *
 * A carriageway on bare ground is a runway. Pavements give it edges, crossings
 * give it junctions, and lamps, trees and parked cars give it the one thing a
 * procedural city is always missing — evidence that somebody uses it.
 *
 * All of it is instanced and laid out along the same walkable graph the
 * simulation navigates, so the dressing agrees with the map by construction
 * rather than by being placed to match it.
 */
function addStreetDressing(
  root: THREE.Group,
  state: GameState,
  lit: LitSurface[],
  rng: () => number,
): void {
  const graph = state.city.graph;
  const dummy = new THREE.Object3D();
  const tint = new THREE.Color();

  const pool = (geometry: THREE.BufferGeometry, material: THREE.Material, capacity: number) => {
    const mesh = new THREE.InstancedMesh(geometry, material, capacity);
    mesh.raycast = () => {}; // scenery is never a target
    mesh.count = 0;
    root.add(mesh);
    return mesh;
  };

  const pavement = pool(
    new THREE.BoxGeometry(1, 0.22, 1),
    new THREE.MeshLambertMaterial({ color: PALETTE.kerb }),
    400,
  );
  const stripes = pool(
    new THREE.PlaneGeometry(1, 1),
    new THREE.MeshLambertMaterial({ color: PALETTE.markings }),
    3000,
  );
  const centreLine = pool(
    new THREE.PlaneGeometry(1, 1),
    new THREE.MeshLambertMaterial({ color: 0xd8b641 }),
    600,
  );
  // Pools of light on the tarmac. Additive, so they brighten what is under them
  // rather than painting over it, and the single biggest thing separating a
  // lit street at night from a row of glowing dots in a void.
  const pools = pool(
    new THREE.CircleGeometry(9.5, 18),
    new THREE.MeshBasicMaterial({
      color: 0xffca7a,
      transparent: true,
      opacity: 0.16,
      blending: THREE.AdditiveBlending,
      depthWrite: false,
      fog: true,
    }),
    400,
  );
  const poles = pool(
    new THREE.CylinderGeometry(0.12, 0.16, 7, 6),
    new THREE.MeshLambertMaterial({ color: 0x5b6166 }),
    400,
  );
  const lamps = pool(
    new THREE.SphereGeometry(0.42, 8, 6),
    new THREE.MeshBasicMaterial({ color: 0xffd9a0, transparent: true, opacity: 0.4 }),
    400,
  );
  const trunks = pool(
    new THREE.CylinderGeometry(0.22, 0.3, 3.2, 6),
    new THREE.MeshLambertMaterial({ color: 0x6b5544 }),
    500,
  );
  const canopies = pool(
    new THREE.IcosahedronGeometry(2.2, 0),
    new THREE.MeshLambertMaterial({ color: 0x5c8a4a, flatShading: true }),
    500,
  );
  const cars = pool(
    new THREE.BoxGeometry(4.3, 1.25, 1.85),
    new THREE.MeshLambertMaterial({ color: 0xffffff }),
    600,
  );
  const cabins = pool(
    new THREE.BoxGeometry(2.1, 0.85, 1.65),
    new THREE.MeshLambertMaterial({ color: 0x1d2733 }),
    600,
  );

  // Streetlights are the one piece of dressing the clock cares about.
  lit.push(
    { material: lamps.material as THREE.Material, day: 0.05, night: 0.95 },
    { material: pools.material as THREE.Material, day: 0, night: 0.34 },
  );

  const place = (mesh: THREE.InstancedMesh, colour?: THREE.Color) => {
    if (mesh.count >= mesh.instanceMatrix.count) return;
    dummy.updateMatrix();
    mesh.setMatrixAt(mesh.count, dummy.matrix);
    if (colour) mesh.setColorAt(mesh.count, colour);
    mesh.count++;
  };

  const drawn = new Set<string>();
  for (const edge of graph.edges.values()) {
    const a = graph.places.get(edge.a);
    const b = graph.places.get(edge.b);
    if (!a || !b || a.indoor || b.indoor) continue;
    const key = [edge.a, edge.b].sort().join("|");
    if (drawn.has(key)) continue;
    drawn.add(key);

    const dx = b.x - a.x;
    const dz = b.y - a.y;
    const length = Math.hypot(dx, dz);
    if (length < 20) continue;
    const heading = -Math.atan2(dz, dx);
    // Along the street, and across it.
    const ux = dx / length;
    const uz = dz / length;
    const px = -uz;
    const pz = ux;

    const at = (along: number, across: number) => ({
      x: a.x + ux * along + px * across,
      z: a.y + uz * along + pz * across,
    });

    // Pavements, both sides.
    for (const side of [1, -1]) {
      const p = at(length / 2, side * (ROAD_HALF + 3));
      dummy.position.set(p.x, 0.11, p.z);
      dummy.rotation.set(0, heading, 0);
      dummy.scale.set(length, 1, 6);
      place(pavement);
    }
    dummy.scale.setScalar(1);

    // Crossings, set back from each junction.
    for (const end of [16, length - 16]) {
      for (let s = -3; s <= 3; s++) {
        const p = at(end, s * 2.6);
        dummy.position.set(p.x, 0.15, p.z);
        dummy.rotation.set(-Math.PI / 2, 0, heading);
        dummy.scale.set(1.1, 5.4, 1);
        place(stripes);
      }
    }
    dummy.scale.setScalar(1);

    // Markings. A carriageway without them is a flat expanse under your feet
    // with no sense of direction or scale, which is exactly how it read before:
    // a double yellow down the middle, white dashes dividing the lanes.
    for (const across of [-0.45, 0.45]) {
      const p = at(length / 2, across);
      dummy.position.set(p.x, 0.15, p.z);
      dummy.rotation.set(-Math.PI / 2, 0, heading);
      dummy.scale.set(length - 24, 0.28, 1);
      place(centreLine);
    }
    for (const across of [-5.6, 5.6]) {
      for (let along = 12; along < length - 12; along += 14) {
        const p = at(along, across);
        dummy.position.set(p.x, 0.15, p.z);
        dummy.rotation.set(-Math.PI / 2, 0, heading);
        dummy.scale.set(4.5, 0.3, 1);
        place(stripes);
      }
    }
    dummy.scale.setScalar(1);

    // Lamps, alternating sides so the street lights evenly.
    let flip = 1;
    for (let along = 24; along < length - 18; along += 40) {
      const side = (flip *= -1);
      const p = at(along, side * (ROAD_HALF + 1.4));
      dummy.rotation.set(0, 0, 0);
      dummy.position.set(p.x, 3.5, p.z);
      place(poles);
      dummy.position.set(p.x, 7.1, p.z);
      place(lamps);
      // The pool sits under the lamp, on the road rather than the pavement.
      dummy.position.set(p.x - px * side * 3, 0.13, p.z - pz * side * 3);
      dummy.rotation.set(-Math.PI / 2, 0, 0);
      place(pools);
    }

    // Trees, offset from the lamps so they do not stand in each other.
    for (let along = 40; along < length - 24; along += 34) {
      const side = rng() > 0.5 ? 1 : -1;
      const p = at(along + rng() * 6, side * (ROAD_HALF + 4.2));
      dummy.rotation.set(0, rng() * Math.PI, 0);
      dummy.position.set(p.x, 1.6, p.z);
      place(trunks);
      dummy.position.set(p.x, 4.3 + rng() * 0.6, p.z);
      dummy.scale.setScalar(0.85 + rng() * 0.45);
      place(canopies);
      dummy.scale.setScalar(1);
    }

    // Parked at the kerb, facing along the street, in colours a city has.
    for (let along = 20; along < length - 20; along += 15 + rng() * 16) {
      if (rng() > 0.62) continue;
      const side = rng() > 0.5 ? 1 : -1;
      const p = at(along, side * (ROAD_HALF - 2.4));
      dummy.rotation.set(0, heading, 0);
      dummy.position.set(p.x, 0.72, p.z);
      tint.setHSL(rng(), 0.15 + rng() * 0.4, 0.28 + rng() * 0.42);
      place(cars, tint);
      dummy.position.set(p.x - ux * 0.4, 1.72, p.z - uz * 0.4);
      place(cabins);
    }
  }

  for (const mesh of [pavement, stripes, centreLine, pools, poles, lamps, trunks, canopies, cars, cabins]) {
    mesh.instanceMatrix.needsUpdate = true;
    if (mesh.instanceColor) mesh.instanceColor.needsUpdate = true;
  }
}

export function buildCity(state: GameState): CityMeshes {
  const root = new THREE.Group();
  const colliders: THREE.Box3[] = [];

  // Deterministic window pattern — same seed, same skyline.
  let seed = 0x9e3779b9;
  const rng = () => {
    seed = (Math.imul(seed ^ (seed >>> 15), seed | 1) + 0x6d2b79f5) >>> 0;
    return (seed >>> 8) / 0xffffff;
  };

  const ground = new THREE.Mesh(
    new THREE.PlaneGeometry(6000, 6000),
    new THREE.MeshLambertMaterial({ color: PALETTE.ground }),
  );
  ground.rotation.x = -Math.PI / 2;
  ground.position.y = -0.4;
  ground.receiveShadow = true;
  root.add(ground);

  const lit: LitSurface[] = [];

  for (const district of state.city.districts.values()) addDistrict(root, district);
  addRoads(root, state);
  addInfill(root, state, colliders, lit, rng);
  addStreetDressing(root, state, lit, rng);

  const landmarks: CityMeshes["landmarks"] = [];
  const interiors: Interior[] = [];
  for (const building of state.city.buildings.values()) {
    addBuilding(root, state, building, colliders, lit, interiors, rng);
    landmarks.push({
      name: building.name,
      position: new THREE.Vector3(
        building.x + building.width / 2,
        building.floors * FLOOR_HEIGHT + 4,
        building.y + building.depth / 2,
      ),
    });
  }

  // No lights here: `sky.ts` owns them, because what they should be doing
  // depends entirely on what time the simulation says it is.
  return { root, colliders, landmarks, lit, interiors };
}

/** Where a place sits in world space. */
export function placePosition(place: Place, out = new THREE.Vector3()): THREE.Vector3 {
  return out.set(place.x, place.floor * FLOOR_HEIGHT, place.y);
}

/** The outdoor place nearest a world position — how free movement rejoins the sim. */
export function nearestOutdoorPlace(state: GameState, x: number, z: number): Place | undefined {
  let best: Place | undefined;
  let bestDistance = Infinity;
  for (const place of state.city.graph.places.values()) {
    if (place.indoor) continue;
    const distance = (place.x - x) ** 2 + (place.y - z) ** 2;
    if (distance < bestDistance) {
      bestDistance = distance;
      best = place;
    }
  }
  return best;
}

/**
 * Where the simulation thinks you are, given where you actually are.
 *
 * Inside a public room the answer comes from that room's own place list, which
 * is what keeps free movement honest: you cannot end up snapped to a staff room
 * by standing near its wall, because a staff room is never in the list.
 */
export function placeAt(
  state: GameState,
  interiors: Interior[],
  x: number,
  y: number,
  z: number,
): Place | undefined {
  for (const interior of interiors) {
    if (x < interior.bounds.min.x || x > interior.bounds.max.x) continue;
    if (z < interior.bounds.min.z || z > interior.bounds.max.z) continue;
    if (y > interior.bounds.max.y + 1) continue;
    let best: Place | undefined;
    let bestDistance = Infinity;
    for (const id of interior.placeIds) {
      const place = state.city.graph.places.get(id);
      if (!place) continue;
      const distance = (place.x - x) ** 2 + (place.y - z) ** 2;
      if (distance < bestDistance) {
        bestDistance = distance;
        best = place;
      }
    }
    if (best) return best;
  }
  return nearestOutdoorPlace(state, x, z);
}
