/**
 * The city, extruded.
 *
 * Everything here is derived from the same `GameState` the 2D terminal uses —
 * no second source of truth. The simulation already works in metres with a
 * floor index, so the mapping is direct: sim `x` is world X, sim `y` is world
 * Z, and a floor becomes height. Nothing about the sim had to change to make it
 * three-dimensional, which is the whole reason it was built coordinate-first.
 */

import * as THREE from "three";

import type { GameState } from "../../src/sim/state.js";
import type { Building, District, Place } from "../../src/world/types.js";

export const FLOOR_HEIGHT = 3.6;

/**
 * Infill.
 *
 * The simulation models eight buildings across roughly a square mile. On a
 * top-down map that is a city; at eye level it is a business park with a lot of
 * car park between the sheds. So the gaps get filled with blocks that are
 * scenery and nothing else — no doors, no rooms, no network, nobody inside.
 *
 * They are the street wall, and the honest way to think about them is as the
 * *rest* of the city: the parts nothing in this game happens in. Everything the
 * game does happen in is still generated by `src/world/`, still has people in
 * it, and is still the only thing labelled.
 *
 * The cells are small on purpose. A cell that straddles a street is dropped
 * whole, so the grid's own coarseness *becomes* the street width: at 44 metres
 * a twenty-metre road came out over a hundred metres wide, and the city read as
 * a ring road with the buildings parked around the edge of it.
 */
const INFILL_CELL = 26;
const INFILL_STEP = 30;
/** Kerb to facade. A street is about twice this wide. */
const STREET_CLEARANCE = 10;
/** Buildings the game is played in get a bit more elbow room than a terrace. */
const BUILDING_CLEARANCE = 8;
const INFILL_CAPACITY = 2400;
const INFILL_WINDOW_CAPACITY = 9000;

export interface CityMeshes {
  root: THREE.Group;
  /** Solid things the player should not walk through. */
  colliders: THREE.Box3[];
  /** Buildings the simulation actually models, for the navigation labels. */
  landmarks: Array<{ name: string; position: THREE.Vector3 }>;
}

/**
 * Night, but a *legible* night.
 *
 * The first pass at this used the terminal client's palette directly — panel
 * greys in the #0e1319 range — and produced a screen that was, correctly and
 * uselessly, black: a Lambert surface multiplies its colour by the light, so
 * a 10%-grey building under a 16%-grey ambient is 1.6% grey. These are the
 * values that survive that multiplication and still read as a night city.
 */
const PALETTE = {
  // Dark ground, lit facades. Up-facing surfaces catch the sky light and
  // side-facing ones do not, so a pavement the same grey as a wall reads
  // *brighter* than the wall and flattens the whole street.
  ground: 0x090d12,
  district: 0x141c25,
  road: 0x2a3745,
  building: 0x3a4c62,
  buildingLit: 0x50697f,
  window: 0x35e0c8,
  kerb: 0x364552,
  /** Infill is a shade colder and duller than anything the game is played in. */
  infill: 0x2e3d4e,
  infillWindow: 0xe8cf94,
};

function box(w: number, h: number, d: number, colour: number, opts: { emissive?: number } = {}) {
  const material = new THREE.MeshLambertMaterial({
    color: colour,
    ...(opts.emissive ? { emissive: opts.emissive, emissiveIntensity: 0.35 } : {}),
  });
  return new THREE.Mesh(new THREE.BoxGeometry(w, h, d), material);
}

/** Lit windows scattered up a facade — the whole reason a night city reads. */
function facadeWindows(building: Building, rng: () => number): THREE.InstancedMesh {
  const perFloor = Math.max(2, Math.floor(building.width / 14));
  const count = perFloor * building.floors * 2;
  const geometry = new THREE.PlaneGeometry(2.2, 1.4);
  const material = new THREE.MeshBasicMaterial({ color: PALETTE.window, transparent: true, opacity: 0.5 });
  const mesh = new THREE.InstancedMesh(geometry, material, count);
  const dummy = new THREE.Object3D();

  let i = 0;
  for (let floor = 0; floor < building.floors; floor++) {
    const y = floor * FLOOR_HEIGHT + FLOOR_HEIGHT * 0.55;
    for (let n = 0; n < perFloor; n++) {
      const t = (n + 0.5) / perFloor;
      for (const [side, rot] of [
        [1, 0],
        [-1, Math.PI],
      ] as const) {
        if (i >= count) break;
        dummy.position.set(
          building.x + t * building.width,
          y,
          building.y + (side > 0 ? building.depth + 0.1 : -0.1),
        );
        dummy.rotation.set(0, rot, 0);
        // Not every window is lit, and the pattern should not look regular.
        dummy.scale.setScalar(rng() > 0.45 ? 1 : 0.001);
        dummy.updateMatrix();
        mesh.setMatrixAt(i++, dummy.matrix);
      }
    }
  }
  mesh.instanceMatrix.needsUpdate = true;
  return mesh;
}

function addDistrict(root: THREE.Group, district: District): void {
  const mesh = box(district.width, 0.4, district.height, PALETTE.district);
  mesh.position.set(district.x + district.width / 2, -0.2, district.y + district.height / 2);
  mesh.receiveShadow = true;
  root.add(mesh);
}

function addBuilding(root: THREE.Group, building: Building, colliders: THREE.Box3[], rng: () => number): void {
  const height = building.floors * FLOOR_HEIGHT;
  const mesh = box(building.width, height, building.depth, PALETTE.building);
  mesh.position.set(building.x + building.width / 2, height / 2, building.y + building.depth / 2);
  mesh.castShadow = true;
  mesh.receiveShadow = true;
  root.add(mesh);

  // A brighter band at street level so the base does not vanish into the road.
  const skirt = box(building.width + 0.6, 1.4, building.depth + 0.6, PALETTE.buildingLit);
  skirt.position.set(building.x + building.width / 2, 0.7, building.y + building.depth / 2);
  root.add(skirt);

  root.add(facadeWindows(building, rng));

  colliders.push(
    new THREE.Box3(
      new THREE.Vector3(building.x - 0.3, 0, building.y - 0.3),
      new THREE.Vector3(building.x + building.width + 0.3, height, building.y + building.depth + 0.3),
    ),
  );
}

/** Roads are drawn along the walkable graph, so the city you see is the city that exists. */
function addRoads(root: THREE.Group, state: GameState): void {
  const graph = state.city.graph;
  const drawn = new Set<string>();

  for (const edge of graph.edges.values()) {
    const a = graph.places.get(edge.a);
    const b = graph.places.get(edge.b);
    if (!a || !b || a.indoor || b.indoor) continue;
    const key = [edge.a, edge.b].sort().join("|");
    if (drawn.has(key)) continue;
    drawn.add(key);

    const dx = b.x - a.x;
    const dz = b.y - a.y;
    const length = Math.hypot(dx, dz);
    if (length < 1) continue;

    const heading = -Math.atan2(dz, dx);
    const road = box(length, 0.12, 22, PALETTE.road);
    road.position.set(a.x + dx / 2, 0.06, a.y + dz / 2);
    road.rotation.y = heading;
    root.add(road);

    // A centre line. Without one the carriageway is a flat tone under your feet
    // and you cannot tell which way the street runs until you have walked it.
    const line = box(length - 6, 0.02, 0.5, PALETTE.kerb);
    line.position.set(a.x + dx / 2, 0.14, a.y + dz / 2);
    line.rotation.y = heading;
    root.add(line);
  }

  // A pad under each outdoor place so junctions and plazas read as somewhere.
  for (const place of graph.places.values()) {
    if (place.indoor) continue;
    const pad = new THREE.Mesh(
      new THREE.CircleGeometry(Math.max(12, place.radius * 0.8), 28),
      new THREE.MeshLambertMaterial({ color: PALETTE.kerb }),
    );
    pad.rotation.x = -Math.PI / 2;
    pad.position.set(place.x, 0.09, place.y);
    root.add(pad);
  }
}

/* ------------------------------------------------------------------ infill */

interface Rect {
  x0: number;
  z0: number;
  x1: number;
  z1: number;
}

/** Everywhere infill must not go: streets, plazas, and the real buildings. */
function keepClear(state: GameState): { rects: Rect[]; segments: Array<[number, number, number, number]> } {
  const rects: Rect[] = [];
  const segments: Array<[number, number, number, number]> = [];

  for (const building of state.city.buildings.values()) {
    rects.push({
      x0: building.x - BUILDING_CLEARANCE,
      z0: building.y - BUILDING_CLEARANCE,
      x1: building.x + building.width + BUILDING_CLEARANCE,
      z1: building.y + building.depth + BUILDING_CLEARANCE,
    });
  }

  const graph = state.city.graph;
  for (const place of graph.places.values()) {
    if (place.indoor) continue;
    // A plaza is not its whole footprint radius of open ground — that reading
    // put the nearest building 350 metres from the spawn point and produced a
    // skyline you could only ever look at.
    const r = place.radius * 0.62 + STREET_CLEARANCE;
    rects.push({ x0: place.x - r, z0: place.y - r, x1: place.x + r, z1: place.y + r });
  }
  for (const edge of graph.edges.values()) {
    const a = graph.places.get(edge.a);
    const b = graph.places.get(edge.b);
    if (!a || !b || a.indoor || b.indoor) continue;
    segments.push([a.x, a.y, b.x, b.y]);
  }

  return { rects, segments };
}

function rectsOverlap(a: Rect, b: Rect): boolean {
  return a.x0 < b.x1 && a.x1 > b.x0 && a.z0 < b.z1 && a.z1 > b.z0;
}

/**
 * Does a street run too close to this block?
 *
 * Measured rect-to-segment, by walking the road and clamping each point onto
 * the rect. Comparing centre-to-segment instead — the obvious version — adds
 * half a block width to every margin, which turned a twenty-metre street into a
 * hundred-metre clearing and hollowed out the middle of every district.
 */
function nearSegment(cell: Rect, seg: [number, number, number, number], margin: number): boolean {
  const [ax, az, bx, bz] = seg;
  const length = Math.hypot(bx - ax, bz - az);
  const steps = Math.max(2, Math.ceil(length / 8));
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    const px = ax + (bx - ax) * t;
    const pz = az + (bz - az) * t;
    const qx = Math.max(cell.x0, Math.min(cell.x1, px));
    const qz = Math.max(cell.z0, Math.min(cell.z1, pz));
    if (Math.hypot(px - qx, pz - qz) < margin) return true;
  }
  return false;
}

/**
 * Two instanced meshes for the entire background city: one for the blocks, one
 * for every lit window in all of them. Several hundred buildings at two draw
 * calls, which is the only reason this is affordable at all.
 */
function addInfill(root: THREE.Group, state: GameState, colliders: THREE.Box3[], rng: () => number): void {
  const clear = keepClear(state);
  const blocks = new THREE.InstancedMesh(
    new THREE.BoxGeometry(1, 1, 1),
    // A little emissive so the far side of a block does not go to pure black
    // under a single directional light.
    new THREE.MeshLambertMaterial({ color: 0xffffff, emissive: 0x0d151d }),
    INFILL_CAPACITY,
  );
  const windows = new THREE.InstancedMesh(
    new THREE.PlaneGeometry(2.6, 1.7),
    new THREE.MeshBasicMaterial({ color: PALETTE.infillWindow, transparent: true, opacity: 0.6 }),
    INFILL_WINDOW_CAPACITY,
  );
  const dummy = new THREE.Object3D();
  const tint = new THREE.Color();
  const parked = new THREE.Vector3(0, -1000, 0);

  let block = 0;
  let lit = 0;

  for (const district of state.city.districts.values()) {
    for (let x = district.x + 8; x + INFILL_CELL < district.x + district.width - 8; x += INFILL_STEP) {
      for (let z = district.y + 8; z + INFILL_CELL < district.y + district.height - 8; z += INFILL_STEP) {
        if (block >= INFILL_CAPACITY) break;
        const cell: Rect = { x0: x, z0: z, x1: x + INFILL_CELL, z1: z + INFILL_CELL };
        if (clear.rects.some((r) => rectsOverlap(cell, r))) continue;
        if (clear.segments.some((s) => nearSegment(cell, s, STREET_CLEARANCE))) continue;

        // A skyline needs a distribution, not a mean: mostly low, occasionally
        // tall, and never the same twice down a street.
        const floors = 2 + Math.floor(rng() ** 2.2 * 13);
        const height = floors * FLOOR_HEIGHT;
        const width = INFILL_CELL - 2 - rng() * 4;
        const depth = INFILL_CELL - 2 - rng() * 4;
        const cx = x + INFILL_CELL / 2;
        const cz = z + INFILL_CELL / 2;

        dummy.position.set(cx, height / 2, cz);
        dummy.rotation.set(0, 0, 0);
        dummy.scale.set(width, height, depth);
        dummy.updateMatrix();
        blocks.setMatrixAt(block, dummy.matrix);
        tint.setHex(PALETTE.infill).offsetHSL((rng() - 0.5) * 0.03, 0, (rng() - 0.5) * 0.09);
        blocks.setColorAt(block, tint);
        block++;

        colliders.push(
          new THREE.Box3(
            new THREE.Vector3(cx - width / 2, 0, cz - depth / 2),
            new THREE.Vector3(cx + width / 2, height, cz + depth / 2),
          ),
        );

        for (let n = 0; n < floors * 2 && lit < INFILL_WINDOW_CAPACITY; n++) {
          if (rng() > 0.4) continue;
          const floor = 1 + Math.floor(rng() * Math.max(1, floors - 1));
          const side = Math.floor(rng() * 4);
          const along = (rng() - 0.5) * (side % 2 === 0 ? width : depth) * 0.7;
          const out = (side % 2 === 0 ? depth : width) / 2 + 0.12;
          dummy.position.set(
            cx + (side === 0 ? along : side === 2 ? along : side === 1 ? out : -out),
            floor * FLOOR_HEIGHT + FLOOR_HEIGHT * 0.5,
            cz + (side === 0 ? out : side === 2 ? -out : along),
          );
          dummy.rotation.set(0, (side * Math.PI) / 2, 0);
          dummy.scale.setScalar(1);
          dummy.updateMatrix();
          windows.setMatrixAt(lit++, dummy.matrix);
        }
      }
    }
  }

  dummy.position.copy(parked);
  dummy.rotation.set(0, 0, 0);
  dummy.scale.setScalar(1);
  dummy.updateMatrix();
  for (let i = block; i < INFILL_CAPACITY; i++) blocks.setMatrixAt(i, dummy.matrix);
  for (let i = lit; i < INFILL_WINDOW_CAPACITY; i++) windows.setMatrixAt(i, dummy.matrix);

  blocks.instanceMatrix.needsUpdate = true;
  windows.instanceMatrix.needsUpdate = true;
  if (blocks.instanceColor) blocks.instanceColor.needsUpdate = true;
  // Scenery is never a target: keep it out of every raycast the client runs.
  blocks.raycast = () => {};
  windows.raycast = () => {};
  root.add(blocks);
  root.add(windows);
}

function lighting(root: THREE.Group): void {
  // Sky above, street-glow below: a hemisphere light does in one object what
  // separate ambient and bounce lights would, and it is the difference between
  // facades that read as vertical and facades that read as flat.
  root.add(new THREE.HemisphereLight(0xaac6de, 0x171d24, 1.9));

  const moon = new THREE.DirectionalLight(0xcfe2f5, 1.5);
  moon.position.set(-400, 600, -300);
  root.add(moon);

  // A cool fill from the opposite side keeps the shadowed sides off black.
  const fill = new THREE.DirectionalLight(0x35e0c8, 0.45);
  fill.position.set(600, 300, 500);
  root.add(fill);
}

export function buildCity(state: GameState): CityMeshes {
  const root = new THREE.Group();
  const colliders: THREE.Box3[] = [];

  // Deterministic window pattern — same seed, same skyline.
  let seed = 0x9e3779b9;
  const rng = () => {
    seed = (Math.imul(seed ^ (seed >>> 15), seed | 1) + 0x6d2b79f5) >>> 0;
    return (seed >>> 8) / 0xffffff;
  };

  const ground = new THREE.Mesh(
    new THREE.PlaneGeometry(6000, 6000),
    new THREE.MeshLambertMaterial({ color: PALETTE.ground }),
  );
  ground.rotation.x = -Math.PI / 2;
  ground.position.y = -0.4;
  ground.receiveShadow = true;
  root.add(ground);

  for (const district of state.city.districts.values()) addDistrict(root, district);
  addRoads(root, state);
  addInfill(root, state, colliders, rng);

  const landmarks: CityMeshes["landmarks"] = [];
  for (const building of state.city.buildings.values()) {
    addBuilding(root, building, colliders, rng);
    landmarks.push({
      name: building.name,
      position: new THREE.Vector3(
        building.x + building.width / 2,
        building.floors * FLOOR_HEIGHT + 4,
        building.y + building.depth / 2,
      ),
    });
  }
  lighting(root);

  return { root, colliders, landmarks };
}

/** Where a place sits in world space. */
export function placePosition(place: Place, out = new THREE.Vector3()): THREE.Vector3 {
  return out.set(place.x, place.floor * FLOOR_HEIGHT, place.y);
}

/** The outdoor place nearest a world position — how free movement rejoins the sim. */
export function nearestOutdoorPlace(state: GameState, x: number, z: number): Place | undefined {
  let best: Place | undefined;
  let bestDistance = Infinity;
  for (const place of state.city.graph.places.values()) {
    if (place.indoor) continue;
    const distance = (place.x - x) ** 2 + (place.y - z) ** 2;
    if (distance < bestDistance) {
      bestDistance = distance;
      best = place;
    }
  }
  return best;
}
